name: mat_month_picker_dialog
description: Material design month picker dialog.
version: 1.1.2
homepage: https://github.com/leoshusar/mat_month_picker_dialog

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  lints: ^1.0.0
